#Choose between different special modes for explosion healing.
[explosion_healing_mode]
	#(Default = "default_mode") Select between any of the following healing modes by copying the string (the text enclosed by the double quotes along with the double quotes)
	#and pasting it into the value of the "mode" setting below:
	#["default_mode", "daytime_healing_mode", "difficulty_based_healing_mode", "blast_resistance_based_healing_mode"] 
	mode = "default_mode"
#Configure which explosions are allowed to heal.
[explosion_sources]
	#(Default = true) Heal explosions caused by Creepers.
	heal_creeper_explosions = true
	#(Default = false) Heal explosions caused by Ghasts.
	heal_ghast_explosions = true
	#(Default = false) Heal explosions caused by Withers.
	heal_wither_explosions = true
	#(Default = false) Heal explosions caused by TNT blocks.
	heal_tnt_explosions = false
	#(Default = false) Heal explosions caused by TNT minecarts.
	heal_tnt_minecart_explosions = false
	#(Default = false) Heal explosions caused by beds and respawn anchors.
	heal_bed_and_respawn_anchor_explosions = false
	#(Default = false) Heal explosions caused by end crystals.
	heal_end_crystal_explosions = false
#These settings allow you to configure whether explosions from specific sources are allowed to drop items or not.
[explosion_item_drops]
	#(Default = true) Explosions caused by Creepers will drop items.
	drop_items_on_creeper_explosions = false
	#(Default = true) Explosions caused by Ghasts will drop items.
	drop_items_on_ghast_explosions = false
	#(Default = true) Explosions caused by Withers will drop items.
	drop_items_on_wither_explosions = false
	#(Default = true) Explosions caused by TNT will drop items.
	drop_items_on_tnt_explosions = true
	#(Default = true) Explosions caused by TNT minecarts will drop items.
	drop_items_on_tnt_minecart_explosions = true
	#(Default = true) Explosions caused by beds and respawn anchors will drop items.
	drop_items_on_bed_and_respawn_anchor_explosions = true
	#(Default = true) Explosions caused by end crystals will drop items.
	drop_items_on_end_crystal_explosions = true
#Configure the delays related to the healing of explosions.
[delays]
	#(Default = 3) Change the delay in seconds between each explosion and its corresponding healing process.
	explosion_heal_delay = 120.0
	#(Default = 1) Change the delay in seconds between each block placement during the explosion healing process.
	block_placement_delay = 0.25
#Toggleable settings to customize the healing of explosions.
[preferences]
	#(Default = true) Whether or not blocks should be healed where there is currently flowing water.
	heal_on_flowing_water = true
	#(Default = false) Whether or not blocks should healed where there is currently a source water block.
	heal_on_source_water = false
	#(Default = true) Whether or not blocks should be healed where there is currently flowing lava.
	heal_on_flowing_lava = true
	#(Default = false) Whether or not blocks should be healed where there is currently a source lava block.
	heal_on_source_lava = false
	#(Default = true) Whether or not a block heal should play a sound effect.
	block_placement_sound_effect = true
	#(Default = true) Makes explosion heal immediately upon throwing a splash potion of Healing on them.
	heal_on_healing_potion_splash = false
	#(Default = true) Makes explosion start their healing process upon throwing a splash potion of Regeneration of them.
	#This option only modifies the heal delay of the explosion and only affects explosions created with the default healing mode.
	heal_on_regeneration_potion_splash = false
	#(Default = false) Enable or disable the usage of the whitelist
	enable_whitelist = false
#Use an optional whitelist to customize which blocks are allowed to heal. To add an entry, specify the block's namespace
#along with its identifier, separated by a colon, and add it in-between the square brackets below. Separate each entry with a comma.
#Example entries:
#whitelist_entries = ["minecraft:grass",  "minecraft:stone", "minecraft:sand"]
[whitelist]
	whitelist_entries = ["minecraft:placeholder"]
#Add your own replace settings to configure which blocks should be used to heal other blocks. The block on the right will be used to heal the block on the left.
#Specify the block's namespace along with the block's name identifier, separated by a colon.
#Example entry:
#"minecraft:gold_block" = "minecraft:stone"
#Warning, the same key cannot appear more than once in the replace map! For example, the following will cause an error:
#"minecraft:diamond_block" = "minecraft:stone"
#"minecraft:diamond_block" = "minecraft:air" 
[replace_map]
	"minecraft:diamond_block" = "minecraft:stone"
