# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# Enable block entities light source.
	block_entities = true
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "fancy"
	beam = true
	guardian_laser = true

			[light_sources.settings.entities.minecraft]
				glow_item_frame = false
				player = true
				tropical_fish = true
				bat = true
				squid = true
				rabbit = true
				axolotl = true
				cow = true
				item = true
				glow_squid = true
				sheep = true
				villager = true
				turtle = true
				chicken = true
				allay = true
				area_effect_cloud = true
				armor_stand = true
				creeper = true
				spider = true
				drowned = true
				enderman = true
				skeleton = true
				zombie = true
				horse = true
				iron_golem = true
				bee = true
				boat = true
				pig = true
				experience_bottle = true
				experience_orb = true
				cat = true
				zombie_villager = true
				zombified_piglin = true
				slime = true
				witch = true
				cod = true
				dolphin = true
				salmon = true
				arrow = true
				fox = true
				wolf = true
				donkey = true
				cave_spider = true
				frog = true
				leash_knot = true
				husk = true
				stray = true
				polar_bear = true
				llama = true
				tnt_minecart = true
				chest_minecart = true
				illusioner = true
				painting = true
				item_frame = true
				parrot = true
				ocelot = true
				pillager = true
				potion = true
				evoker = true
				vindicator = true
				lightning_bolt = true
				goat = true
				blaze = true
				block_display = true
				chest_boat = true
				camel = true
				dragon_fireball = true
				elder_guardian = true
				end_crystal = true
				ender_dragon = true
				endermite = true
				evoker_fangs = true
				eye_of_ender = true
				falling_block = true
				fireball = true
				firework_rocket = true
				fishing_bobber = true
				ghast = true
				giant = true
				guardian = true
				hoglin = true
				interaction = true
				item_display = true
				llama_spit = true
				magma_cube = true
				marker = true
				minecart = true
				command_block_minecart = true
				furnace_minecart = true
				hopper_minecart = true
				spawner_minecart = true
				mooshroom = true
				mule = true
				panda = true
				phantom = true
				piglin = true
				piglin_brute = true
				tnt = true
				pufferfish = true
				ravager = true
				shulker = true
				shulker_bullet = true
				silverfish = true
				skeleton_horse = true
				small_fireball = true
				sniffer = true
				snow_golem = true
				snowball = true
				spectral_arrow = true
				strider = true
				tadpole = true
				text_display = true
				egg = true
				ender_pearl = true
				trader_llama = true
				trident = true
				vex = true
				wandering_trader = true
				warden = true
				wither = true
				wither_skeleton = true
				wither_skull = true
				zoglin = true
				zombie_horse = true

			[light_sources.settings.entities.naturalist]
				deer = true
				coral_snake = true
				butterfly = true
				snake = true
				lizard = true
				bear = true
				firefly = true
				bluejay = true
				canary = true
				bass = true
				finch = true
				boar = true
				robin = true
				cardinal = true
				snail = true
				sparrow = true
				duck = true
				lion = true
				zebra = true
				rattlesnake = true
				rhino = true
				catfish = true
				alligator = true
				caterpillar = true
				dragonfly = true
				elephant = true
				giraffe = true
				hippo = true
				lizard_tail = true
				tortoise = true
				vulture = true
				duck_egg = true
				moose = true

			[light_sources.settings.entities.supplementaries]
				red_merchant = true

			[light_sources.settings.entities.majruszsdifficulty]
				illusioner = true
				tank = true
				creeperling = true
				cerberus = true
				cursed_armor = true
				giant = true

			[light_sources.settings.entities.friendsandfoes]
				glare = true
				copper_golem = true
				moobloom = true
				rascal = true
				mauler = true
				iceologer = true
				crab = true
				player_illusion = true
				tuff_golem = true
				wildfire = true
				ice_chunk = true

			[light_sources.settings.entities.niftycarts]
				animal_cart = true
				hand_cart = true
				plow = true
				postilion = true
				supply_cart = true

			[light_sources.settings.entities.handcrafted]
				fancy_painting = true
				seat = true

			[light_sources.settings.entities.farmersdelight]
				rotten_tomato = true

			[light_sources.settings.entities.snowrealmagic]
				snow = true

[debug]
	active_dynamic_lighting_cells = false
	display_dynamic_lighting_chunk_rebuild = false
	display_behavior_bounding_box = false
